// UMD env: NO modules. Disponible como window.ENV
window.ENV = {
  PAYPAL_CLIENT_ID: "",
  PAYPAL_SECRET: "",
  PAYPAL_PLAN_MONTHLY_1499: "",
  PAYPAL_PLAN_ANNUAL_4999: "",
  PAYPAL_WEBHOOK_ID: "",
  CRISP_WEBSITE_ID: "",
  JUICYADS_ZONE: "",
  EXOCLICK_ZONE: "",
  EROADVERTISING_ZONE: "",
  POPADS_SITE_ID: "",
  EXOCLICK_SNIPPET_B64: "",
  JUICYADS_SNIPPET_B64: "",
  EROADVERTISING_SNIPPET_B64: "",
  IBG_ASSETS_BASE_URL: ""
};
