// BeachGirl.pics - Full Images Content Data PART 2
const fullImages_Part2 = [
    { src: '/full/K6AqNa8lHyPw8rujRCux.webp', title: 'Beach Paradise K6AqNa8l', isNew: false },
    { src: '/full/KRGZrnrhKdEiv6bUM0B8.webp', title: 'Beach Paradise KRGZrnrh', isNew: false },
    { src: '/full/KSIgono33EvDrKQDut47.webp', title: 'Beach Paradise KSIgono3', isNew: false },
    { src: '/full/KSft2d50fGqVzjnvaQsP.webp', title: 'Beach Paradise KSft2d50', isNew: false },
    { src: '/full/McOBxMX6PoUZbroTTgP4.webp', title: 'Beach Paradise McOBxMX6', isNew: false },
    { src: '/full/NDGfqsuUip0F4dU9wgVL.webp', title: 'Beach Paradise NDGfqsuU', isNew: false },
    { src: '/full/NDH6z4lZlrQn9bJrR8sl.webp', title: 'Beach Paradise NDH6z4lZ', isNew: false },
    { src: '/full/NqO93fUipM4zuYSCRSt5.webp', title: 'Beach Paradise NqO93fUi', isNew: false },
    { src: '/full/NzzddX28psM9wi68V6CK.webp', title: 'Beach Paradise NzzddX28', isNew: false },
    { src: '/full/PYxGx0lKZ43QPf1qdvLZ.webp', title: 'Beach Paradise PYxGx0lK', isNew: false },
    { src: '/full/QrxqDwp4XM84wYYND3uT.webp', title: 'Beach Paradise QrxqDwp4', isNew: false },
    { src: '/full/RwJSQRDcYLUL3itNeBsI.webp', title: 'Beach Paradise RwJSQRDc', isNew: false },
    { src: '/full/SPz0O8J0T6G5uVWIoDzQ.webp', title: 'Beach Paradise SPz0O8J0', isNew: false },
    { src: '/full/Sinoseup.webp', title: 'Beach Paradise Sinoseup', isNew: false },
    { src: '/full/Sinportada.webp', title: 'Beach Paradise Sinporta', isNew: false },
    { src: '/full/Sintulo.webp', title: 'Beach Paradise Sintulo.', isNew: false },
    { src: '/full/Siulo.webp', title: 'Beach Paradise Siulo.we', isNew: false },
    { src: '/full/SjBLvi1GzPoLQ1P50c46.webp', title: 'Beach Paradise SjBLvi1G', isNew: false },
    { src: '/full/Sütulo3.webp', title: 'Beach Paradise Sütulo3', isNew: false },
    { src: '/full/TVuPPIBhFDMDCmBdsceB.webp', title: 'Beach Paradise TVuPPIBh', isNew: false },
    { src: '/full/TobOdyqnZJAURlf9gAMN.webp', title: 'Beach Paradise TobOdyqn', isNew: false },
    { src: '/full/TrDWwizZldJ8aKtrTcG1.webp', title: 'Beach Paradise TrDWwizZ', isNew: false },
    { src: '/full/UY3djnFnYQxf0fCsdlnM.webp', title: 'Beach Paradise UY3djnFn', isNew: false },
    { src: '/full/V9GKbtJQTNaM8l93aw36.webp', title: 'Beach Paradise V9GKbtJQ', isNew: false },
    { src: '/full/VRSLM5s8qnZxP1QVoodG.webp', title: 'Beach Paradise VRSLM5s8', isNew: false },
    { src: '/full/W9CK51Mronx3uf5hfQ3U.webp', title: 'Beach Paradise W9CK51Mr', isNew: false },
    { src: '/full/WuoJZZ1KY40aGXaYQ3Md.webp', title: 'Beach Paradise WuoJZZ1K', isNew: false },
    { src: '/full/XdVpvijn3dM2vO9l7gDo.webp', title: 'Beach Paradise XdVpvijn', isNew: false },
    { src: '/full/YKgqQquc9tAsRWIrAmAC.webp', title: 'Beach Paradise YKgqQquc', isNew: false },
    { src: '/full/Z1PRTgXZcRtlo6S85wI6.webp', title: 'Beach Paradise Z1PRTgXZ', isNew: false },
    { src: '/full/ZYIL77u1RSeFdP5wkciw.webp', title: 'Beach Paradise ZYIL77u1', isNew: false },
    { src: '/full/ZyCZwfSUvhPNt480NIda.webp', title: 'Beach Paradise ZyCZwfSU', isNew: false },
    { src: '/full/aYu9xiAT1TlEG6wvm34K.webp', title: 'Beach Paradise aYu9xiAT', isNew: false },
    { src: '/full/backbikini.webp', title: 'Beach Paradise backbiki', isNew: false },
    { src: '/full/bikback2.webp', title: 'Beach Paradise bikback2', isNew: false },
    { src: '/full/bikbanner.webp', title: 'Beach Paradise bikbanne', isNew: false },
    { src: '/full/bikbanner2.webp', title: 'Beach Paradise bikbanne', isNew: false },
    { src: '/full/bikini.webp', title: 'Beach Paradise bikini.w', isNew: false },
    { src: '/full/bikini3.webp', title: 'Beach Paradise bikini3.', isNew: false },
    { src: '/full/bikini5.webp', title: 'Beach Paradise bikini5.', isNew: false },
];

if (typeof module !== 'undefined' && module.exports) { module.exports = { fullImages_Part2 }; }
