// BeachGirl.pics - Full Images Content Data (ALL 127 FILES)
const fullImages = [
    { src: '/full/0456996c-b56e-42ef-9049-56b1a1ae2646.webp', title: 'Beach Paradise 0456996c', isNew: false },
    { src: '/full/0Tc8Vtd0mEIvNHZwYGBq.webp', title: 'Beach Paradise 0Tc8Vtd0', isNew: false },
    { src: '/full/0lySugcO4Pp4pEZKvz9U.webp', title: 'Beach Paradise 0lySugcO', isNew: false },
    { src: '/full/0nSaCJQxbVw4BDrhnhHO.webp', title: 'Beach Paradise 0nSaCJQx', isNew: false },
    { src: '/full/13TXvyRVZ7LtvAOx7kme.webp', title: 'Beach Paradise 13TXvyRV', isNew: false },
    { src: '/full/18VQaczW5kdfdiqUVasH.webp', title: 'Beach Paradise 18VQaczW', isNew: false },
    { src: '/full/1dEu25K0mS3zxRlXRjHR.webp', title: 'Beach Paradise 1dEu25K0', isNew: false },
    { src: '/full/1qEBcg9QbkZRRdLt0Chc.webp', title: 'Beach Paradise 1qEBcg9Q', isNew: false },
    { src: '/full/1tt8H4fX3XzyV90HjNG3.webp', title: 'Beach Paradise 1tt8H4fX', isNew: false },
    { src: '/full/27bGIzFFpej5ubUkvykD.webp', title: 'Beach Paradise 27bGIzFF', isNew: false },
    { src: '/full/2gjqH68H586TKLDK9lh9.webp', title: 'Beach Paradise 2gjqH68H', isNew: false },
    { src: '/full/2yw4sowPh3Tyln5oxRdw.webp', title: 'Beach Paradise 2yw4sowP', isNew: false },
    { src: '/full/39GYGt3bticS0Mjbud0p.webp', title: 'Beach Paradise 39GYGt3b', isNew: false },
    { src: '/full/3IWka3fnP9b8yz6j5l91.webp', title: 'Beach Paradise 3IWka3fn', isNew: false },
    { src: '/full/3ZYL4GCUOs3rfq3iTPJ7.webp', title: 'Beach Paradise 3ZYL4GCU', isNew: false },
    { src: '/full/4GN6i0Db2hl4Ck9vf0LE.webp', title: 'Beach Paradise 4GN6i0Db', isNew: false },
    { src: '/full/4YhoIAWSbVaOqBhAOGqR.webp', title: 'Beach Paradise 4YhoIAWS', isNew: false },
    { src: '/full/82KxJ9daxf9MpK019L5I.webp', title: 'Beach Paradise 82KxJ9da', isNew: false },
    { src: '/full/83cSC4eRnYGZUNo9AoqD.webp', title: 'Beach Paradise 83cSC4eR', isNew: false },
    { src: '/full/85158b64-4168-45fa-9cb4-0b40634f7fa1.webp', title: 'Beach Paradise 85158b64', isNew: false },
    { src: '/full/8faf42TRuGOU4ZW9KS9W.webp', title: 'Beach Paradise 8faf42TR', isNew: false },
    { src: '/full/92Ck0v3g8gZLEQ5vOmpd.webp', title: 'Beach Paradise 92Ck0v3g', isNew: false },
    { src: '/full/993acHdsWLzG80gAFZQs.webp', title: 'Beach Paradise 993acHds', isNew: false },
    { src: '/full/9D5U5fKXT72xnpqsgUaD.webp', title: 'Beach Paradise 9D5U5fKX', isNew: false },
    { src: '/full/9v20KsJFZoAv2WQ8m3o2.webp', title: 'Beach Paradise 9v20KsJF', isNew: false },
    { src: '/full/AHKAq0biFDUtkxlx7TCu.webp', title: 'Beach Paradise AHKAq0bi', isNew: false },
    { src: '/full/ANhHtA0GivBfeAo6dvJG.webp', title: 'Beach Paradise ANhHtA0G', isNew: false },
    { src: '/full/AwKXjDqrJMTKNvB84iRy.webp', title: 'Beach Paradise AwKXjDqr', isNew: false },
    { src: '/full/CTyCcna8JSPObRQpulKJ.webp', title: 'Beach Paradise CTyCcna8', isNew: false },
    { src: '/full/CmxJm1VLBBhvZoUwxWTJ.webp', title: 'Beach Paradise CmxJm1VL', isNew: false },
    { src: '/full/CuX7zQzCBToIMKBYVcA8.webp', title: 'Beach Paradise CuX7zQzC', isNew: false },
    { src: '/full/D3QdNfIR9B8YKPIYl0Hg.webp', title: 'Beach Paradise D3QdNfIR', isNew: false },
    { src: '/full/FElwiy3A7OtgubeV9Qsh.webp', title: 'Beach Paradise FElwiy3A', isNew: false },
    { src: '/full/Fz2ORrJSrERl0BZGOH24.webp', title: 'Beach Paradise Fz2ORrJS', isNew: false },
    { src: '/full/G4YdNFtdunscrnPe5Qb6.webp', title: 'Beach Paradise G4YdNFtd', isNew: false },
    { src: '/full/G5tR4rjmD4dWct9aKfMu.webp', title: 'Beach Paradise G5tR4rjm', isNew: false },
    { src: '/full/I2enQjaFiBfPB2hml0xQ.webp', title: 'Beach Paradise I2enQjaF', isNew: false },
    { src: '/full/ICDQwh9QLaL3SpYTmk4i.webp', title: 'Beach Paradise ICDQwh9Q', isNew: false },
    { src: '/full/IXCJwuZEjxFfPTinm4Cq.webp', title: 'Beach Paradise IXCJwuZE', isNew: false },
    { src: '/full/Jc4OmrYPCcAkzNGKXhE1.webp', title: 'Beach Paradise Jc4OmrYP', isNew: false },
];

if (typeof module !== 'undefined' && module.exports) { module.exports = { fullImages }; }
