window.__ENV = {
  IBG_ASSETS_BASE_URL: "",
  PAYPAL_CLIENT_ID: "",
  PAYPAL_PLAN_MONTHLY_1499: "",
  PAYPAL_PLAN_ANNUAL_4999: "",
  LIFETIME_PRICE_EUR: "49.00",
  PRICE_IMAGE_EUR: "0.10",
  PRICE_VIDEO_EUR: "0.30",
  CRISP_WEBSITE_ID: "",
  EXOCLICK_ZONE: "",
  JUICYADS_ZONE: "",
  JUICYADS_SNIPPET_B64: "",
  EROADVERTISING_ZONE: "",
  EROADVERTISING_SNIPPET_B64: "",
  POPADS_ENABLE: "",
  POPADS_SITE_ID: ""
};
