#!/usr/bin/env bash
set -euo pipefail

TEAM="oriols-projects-ed6b9b04"
PROJECT="ibizagirl-final"
DOMAIN="ibizagirl.pics"

need(){ command -v "$1" >/dev/null || { echo "Falta $1"; exit 1; }; }
need git; need awk; need sed; command -v vercel >/dev/null || npm i -g vercel@latest >/dev/null

# 0) Backup
ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$ROOT"
BK="ibg_backup_$(date +%Y%m%d_%H%M%S)"
mkdir -p "$BK"
cp -a index.html "$BK"/ 2>/dev/null || true

# 1) Crear env.js (SOLO valores públicos; NUNCA secretos)
cat > env.js <<'JS'
// Auto-generated by ibg_home_prepare.sh — NO pongas secretos aquí
window.IBG_ENV = {
  PAYPAL_CLIENT_ID: "AfQEdiielw5fm3wF08p9pcxwqR3gPz82YRNUTKY4A8WNG9AktiGsDNyr2i7BsjVzSwwpeCwR7Tt7DPq5",
  PAYPAL_PLAN_MONTHLY_1499: "P-3WE8037612641383DNCUKNJI",
  PAYPAL_PLAN_ANNUAL_4999:  "P-43K261214Y571983RNCUKN7I",
  CRISP_WEBSITE_ID: "59e184b1-e679-4c93-b3ea-d60b63c1c04c",
  POPADS_ENABLE: true,
  JUICYADS_ZONE: "1099637",
  EXOCLICK_ZONE: "5696328",
  EROADVERTISING_ZONE: "8177575",
  IBG_ASSETS_BASE_URL: "https://ibizagirl-assets.s3.eu-north-1.amazonaws.com"
};
JS

# 2) Asegurar <script src="env.js"> antes de cerrar </head>
if ! grep -qi 'src=["'\'']env\.js["'\'']' index.html; then
  awk '
    BEGIN{IGNORECASE=1}
    /<\/head>/ && !done{
      print "  <script src=\"env.js\"></script>";
      done=1
    }
    {print}
  ' index.html > index.html.__tmp && mv index.html.__tmp index.html
  echo "＋ Inyectado <script src=\"env.js\"> en <head>"
fi

# 3) Forzar https en recursos (evitar mixed content)
if grep -q 'http://' index.html; then
  # macOS/BSD sed -i '' ; GNU sed -i
  if sed --version >/dev/null 2>&1; then sed -i 's#http://#https://#g' index.html; else sed -i '' 's#http://#https://#g' index.html; fi
  echo "↺ Reescritos http:// → https:// en index.html"
fi

# 4) Registrar Service Worker si no existe snippet
if [ -f service-worker.js ] && ! grep -q 'navigator.serviceWorker.register' index.html; then
  awk '
    BEGIN{IGNORECASE=1}
    /<\/body>/ && !done{
      print "<script>if(\"serviceWorker\" in navigator){window.addEventListener(\"load\",()=>{navigator.serviceWorker.register(\"/service-worker.js\").catch(()=>{});});}</script>";
      done=1
    }
    {print}
  ' index.html > index.html.__tmp && mv index.html.__tmp index.html
  echo "＋ Inyectado registro de service-worker"
fi

# 5) Auditoría básica de enlaces CSS/JS referenciados por index.html
echo "== Auditoría de referencias (index.html) =="
REFS=$(awk -F\" '
  BEGIN{IGNORECASE=1}
  /<(script|link)[^>]+(src|href)=/ {
    for(i=1;i<=NF;i++){
      if($i ~ /\.(js|css)(\?|#|$)/){gsub(/#.*/,"",$i); gsub(/\?.*/,"",$i); print $i}
    }
  }' index.html | sort -u)
missing=0
echo "$REFS" | while read -r p; do
  test -z "$p" && continue
  f="${p#./}"; f="${f%%\?*}"
  if [ -f "$f" ]; then echo "✓ $p"; else echo "❌ Falta $p"; missing=1; fi
done

# 6) Commit + Deploy
git add -A
git commit -m "ibg: inject env.js (public), SW registration, https fixes for home" || true
vercel link --project "$PROJECT" --scope "$TEAM" --yes >/dev/null || true
vercel --prod --yes --scope "$TEAM" || true

echo "== Verificación HTTP =="
curl -sSIL "https://$DOMAIN/" | sed -n '1,8p'

echo "Hecho. Abre la home y revisa F12 (Consola + Network)."
