#!/usr/bin/env bash
set -euo pipefail
ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"

# Variables tal cual en Vercel (si alguna no existe, queda vacía)
: "${PAYPAL_CLIENT_ID:=}"
: "${PAYPAL_SECRET:=}"
: "${PAYPAL_PLAN_MONTHLY_1499:=}"
: "${PAYPAL_PLAN_ANNUAL_4999:=}"
: "${PAYPAL_WEBHOOK_ID:=}"
: "${CRISP_WEBSITE_ID:=}"
: "${EXOCLICK_ZONE:=}"
: "${JUICYADS_ZONE:=}"
: "${EROADVERTISING_ZONE:=}"
: "${EXOCLICK_SNIPPET_B64:=}"
: "${JUICYADS_SNIPPET_B64:=}"
: "${EROADVERTISING_SNIPPET_B64:=}"
: "${POPADS_SITE_ID:=}"
: "${POPADS_ENABLE:=0}"
: "${IBG_ASSETS_BASE_URL:=}"

cat > "$ROOT_DIR/env.js" <<JS
// generated by build-env.sh
window.IBG = {
  PAYPAL_CLIENT_ID: "${PAYPAL_CLIENT_ID}",
  PAYPAL_SECRET: "${PAYPAL_SECRET}",
  PAYPAL_PLAN_MONTHLY_1499: "${PAYPAL_PLAN_MONTHLY_1499}",
  PAYPAL_PLAN_ANNUAL_4999: "${PAYPAL_PLAN_ANNUAL_4999}",
  PAYPAL_WEBHOOK_ID: "${PAYPAL_WEBHOOK_ID}",
  CRISP_WEBSITE_ID: "${CRISP_WEBSITE_ID}",
  EXOCLICK_ZONE: "${EXOCLICK_ZONE}",
  JUICYADS_ZONE: "${JUICYADS_ZONE}",
  EROADVERTISING_ZONE: "${EROADVERTISING_ZONE}",
  EXOCLICK_SNIPPET_B64: "${EXOCLICK_SNIPPET_B64}",
  JUICYADS_SNIPPET_B64: "${JUICYADS_SNIPPET_B64}",
  EROADVERTISING_SNIPPET_B64: "${EROADVERTISING_SNIPPET_B64}",
  POPADS_SITE_ID: "${POPADS_SITE_ID}",
  POPADS_ENABLE: "${POPADS_ENABLE}",
  IBG_ASSETS_BASE_URL: "${IBG_ASSETS_BASE_URL}",
  CURRENCY: "EUR"
};
JS

# por si quedó un env.js viejo en tools/, lo eliminamos
rm -f "$ROOT_DIR/tools/env.js"

# por si alguien metió 'export' accidentalmente, lo limpiamos (macOS sed)
sed -i "" -e '1s/^export[[:space:]]\+//' "$ROOT_DIR/env.js" || true

echo "✅ env.js escrito en raíz (sin export)"
