#!/usr/bin/env bash
set -euo pipefail
PAYPAL_CLIENT_ID="${PAYPAL_CLIENT_ID:-}"
PAYPAL_SECRET="${PAYPAL_SECRET:-}"
PAYPAL_PLAN_MONTHLY_1499="${PAYPAL_PLAN_MONTHLY_1499:-}"
PAYPAL_PLAN_ANNUAL_4999="${PAYPAL_PLAN_ANNUAL_4999:-}"
PAYPAL_WEBHOOK_ID="${PAYPAL_WEBHOOK_ID:-}"
CRISP_WEBSITE_ID="${CRISP_WEBSITE_ID:-}"
EXOCLICK_ZONE="${EXOCLICK_ZONE:-}"
JUICYADS_ZONE="${JUICYADS_ZONE:-}"
EROADVERTISING_ZONE="${EROADVERTISING_ZONE:-}"
EXOCLICK_SNIPPET_B64="${EXOCLICK_SNIPPET_B64:-}"
JUICYADS_SNIPPET_B64="${JUICYADS_SNIPPET_B64:-}"
EROADVERTISING_SNIPPET_B64="${EROADVERTISING_SNIPPET_B64:-}"
POPADS_SITE_ID="${POPADS_SITE_ID:-}"
POPADS_ENABLE="${POPADS_ENABLE:-0}"
IBG_ASSETS_BASE_URL="${IBG_ASSETS_BASE_URL:-}"
CURRENCY="EUR"
cat > env.js <<EOJS
window.IBG = {
  PAYPAL_CLIENT_ID: "${PAYPAL_CLIENT_ID}",
  PAYPAL_SECRET: "${PAYPAL_SECRET}",
  PAYPAL_PLAN_MONTHLY_1499: "${PAYPAL_PLAN_MONTHLY_1499}",
  PAYPAL_PLAN_ANNUAL_4999: "${PAYPAL_PLAN_ANNUAL_4999}",
  PAYPAL_WEBHOOK_ID: "${PAYPAL_WEBHOOK_ID}",
  CRISP_WEBSITE_ID: "${CRISP_WEBSITE_ID}",
  EXOCLICK_ZONE: "${EXOCLICK_ZONE}",
  JUICYADS_ZONE: "${JUICYADS_ZONE}",
  EROADVERTISING_ZONE: "${EROADVERTISING_ZONE}",
  EXOCLICK_SNIPPET_B64: "${EXOCLICK_SNIPPET_B64}",
  JUICYADS_SNIPPET_B64: "${JUICYADS_SNIPPET_B64}",
  EROADVERTISING_SNIPPET_B64: "${EROADVERTISING_SNIPPET_B64}",
  POPADS_SITE_ID: "${POPADS_SITE_ID}",
  POPADS_ENABLE: "${POPADS_ENABLE}",
  IBG_ASSETS_BASE_URL: "${IBG_ASSETS_BASE_URL}",
  CURRENCY: "${CURRENCY}"
};
EOJS
echo "✅ env.js generado"
