#!/usr/bin/env bash
set -e
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
mkdir -p "$ROOT/js"

# Variables tal y como las tienes en Vercel, con fallback inocuo
PAYPAL_CLIENT_ID="${PAYPAL_CLIENT_ID:-AfQEdiielw5fm3wF08p9pcxwqR3gPz82YRNUTKY4A8WNG9AktiGsDNyr2i7BsjVzSwwpeCwR7Tt7DPq5}"
PAYPAL_SECRET="${PAYPAL_SECRET:-}"
PAYPAL_PLAN_MONTHLY="${PAYPAL_PLAN_MONTHLY_1499:-P-3WE8037612641383DNCUKNJI}"
PAYPAL_PLAN_YEARLY="${PAYPAL_PLAN_ANNUAL_4999:-P-43K261214Y571983RNCUKN7I}"
PAYPAL_WEBHOOK_ID="${PAYPAL_WEBHOOK_ID:-}"

EXOCLICK_ZONE="${EXOCLICK_ZONE:-5696328}"
JUICYADS_ZONE="${JUICYADS_ZONE:-1099637}"
EROADVERTISING_ZONE="${EROADVERTISING_ZONE:-8177575}"
POPADS_SITE_ID="${POPADS_SITE_ID:-}"
POPADS_ENABLE="${POPADS_ENABLE:-}"

CRISP_WEBSITE_ID="${CRISP_WEBSITE_ID:-59e184b1-e679-4c93-b3ea-d60b63c1c04c}"

IBG_ASSETS_BASE_URL="${IBG_ASSETS_BASE_URL:-}"

EXOCLICK_SNIPPET_B64="${EXOCLICK_SNIPPET_B64:-}"
JUICYADS_SNIPPET_B64="${JUICYADS_SNIPPET_B64:-}"
EROADVERTISING_SNIPPET_B64="${EROADVERTISING_SNIPPET_B64:-}"

PUBLIC_ENVIRONMENT="${PUBLIC_ENVIRONMENT:-production}"
PUBLIC_CURRENCY="${PUBLIC_CURRENCY:-EUR}"

# No depender de python: si hay snippet en B64 y hay "base64" disponible, se decodifica; si no, cadena vacía
decode_b64() {
  local s="$1"
  if [ -z "$s" ]; then echo ""; return 0; fi
  if command -v base64 >/dev/null 2>&1; then
    printf "%s" "$s" | base64 -d 2>/dev/null || echo ""
  else
    echo ""
  fi
}

EXOCLICK_SNIPPET="$(decode_b64 "$EXOCLICK_SNIPPET_B64")"
JUICYADS_SNIPPET="$(decode_b64 "$JUICYADS_SNIPPET_B64")"
EROADVERTISING_SNIPPET="$(decode_b64 "$EROADVERTISING_SNIPPET_B64")"

gen() {
cat > "$1" <<EOT
export const ENV = {
  PAYPAL_CLIENT_ID: "${PAYPAL_CLIENT_ID}",
  PAYPAL_SECRET: "${PAYPAL_SECRET}",
  PAYPAL_PLAN_MONTHLY: "${PAYPAL_PLAN_MONTHLY}",
  PAYPAL_PLAN_YEARLY: "${PAYPAL_PLAN_YEARLY}",
  PAYPAL_WEBHOOK_ID: "${PAYPAL_WEBHOOK_ID}",

  EXOCLICK_ZONE_ID: "${EXOCLICK_ZONE}",
  JUICYADS_ZONE_ID: "${JUICYADS_ZONE}",
  EROADVERTISING_ZONE_ID: "${EROADVERTISING_ZONE}",
  POPADS_SITE_ID: "${POPADS_SITE_ID}",
  POPADS_ENABLE: "${POPADS_ENABLE}",

  CRISP_WEBSITE_ID: "${CRISP_WEBSITE_ID}",

  IBG_ASSETS_BASE_URL: "${IBG_ASSETS_BASE_URL}",

  EXOCLICK_SNIPPET: \`${EXOCLICK_SNIPPET}\`,
  JUICYADS_SNIPPET: \`${JUICYADS_SNIPPET}\`,
  EROADVERTISING_SNIPPET: \`${EROADVERTISING_SNIPPET}\`,

  ENVIRONMENT: "${PUBLIC_ENVIRONMENT}",
  CURRENCY: "${PUBLIC_CURRENCY}"
};
if (typeof window !== "undefined") {
  window.ENV = ENV;
  window.PAYPAL_CLIENT_ID = ENV.PAYPAL_CLIENT_ID;
  window.PAYPAL_PLAN_MONTHLY = ENV.PAYPAL_PLAN_MONTHLY;
  window.PAYPAL_PLAN_YEARLY  = ENV.PAYPAL_PLAN_YEARLY;
  window.PAYPAL_WEBHOOK_ID = ENV.PAYPAL_WEBHOOK_ID;
  window.EXOCLICK_ZONE_ID = ENV.EXOCLICK_ZONE_ID;
  window.JUICYADS_ZONE_ID = ENV.JUICYADS_ZONE_ID;
  window.EROADVERTISING_ZONE_ID = ENV.EROADVERTISING_ZONE_ID;
  window.POPADS_SITE_ID = ENV.POPADS_SITE_ID;
  window.POPADS_ENABLE = ENV.POPADS_ENABLE;
  window.CRISP_WEBSITE_ID = ENV.CRISP_WEBSITE_ID;
  window.IBG_ASSETS_BASE_URL = ENV.IBG_ASSETS_BASE_URL;
  window.EXOCLICK_SNIPPET = ENV.EXOCLICK_SNIPPET;
  window.JUICYADS_SNIPPET = ENV.JUICYADS_SNIPPET;
  window.EROADVERTISING_SNIPPET = ENV.EROADVERTISING_SNIPPET;
}
EOT
}

gen "$ROOT/js/env.js"
gen "$ROOT/env.js"
echo "env.js listo (safe)"
