#!/usr/bin/env bash
set -euo pipefail
ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"

: "${PAYPAL_CLIENT_ID:=}"
: "${PAYPAL_SECRET:=}"
: "${PAYPAL_PLAN_MONTHLY_1499:=}"
: "${PAYPAL_PLAN_ANNUAL_4999:=}"
: "${PAYPAL_WEBHOOK_ID:=}"

: "${CRISP_WEBSITE_ID:=}"

: "${EXOCLICK_ZONE:=}"
: "${JUICYADS_ZONE:=}"
: "${EROADVERTISING_ZONE:=}"

: "${EXOCLICK_SNIPPET_B64:=}"
: "${JUICYADS_SNIPPET_B64:=}"
: "${EROADVERTISING_SNIPPET_B64:=}"

: "${POPADS_SITE_ID:=}"
: "${POPADS_ENABLE:=0}"

: "${IBG_ASSETS_BASE_URL:=}"
CURRENCY="EUR"

cat > "$ROOT_DIR/env.js" <<'EOM'
window.IBG = {
  PAYPAL_CLIENT_ID: "PAYPAL_CLIENT_ID",
  PAYPAL_SECRET: "PAYPAL_SECRET",
  PAYPAL_PLAN_MONTHLY_1499: "PAYPAL_PLAN_MONTHLY_1499",
  PAYPAL_PLAN_ANNUAL_4999: "PAYPAL_PLAN_ANNUAL_4999",
  PAYPAL_WEBHOOK_ID: "PAYPAL_WEBHOOK_ID",
  CRISP_WEBSITE_ID: "CRISP_WEBSITE_ID",
  EXOCLICK_ZONE: "EXOCLICK_ZONE",
  JUICYADS_ZONE: "JUICYADS_ZONE",
  EROADVERTISING_ZONE: "EROADVERTISING_ZONE",
  EXOCLICK_SNIPPET_B64: "EXOCLICK_SNIPPET_B64",
  JUICYADS_SNIPPET_B64: "JUICYADS_SNIPPET_B64",
  EROADVERTISING_SNIPPET_B64: "EROADVERTISING_SNIPPET_B64",
  POPADS_SITE_ID: "POPADS_SITE_ID",
  POPADS_ENABLE: "POPADS_ENABLE",
  IBG_ASSETS_BASE_URL: "IBG_ASSETS_BASE_URL",
  CURRENCY: "EUR"
};
EOM

# Sustituye placeholders por valores de entorno si existen
# (mantiene vacío si no están definidos en Vercel/local)
sed -i "" -e "s#PAYPAL_CLIENT_ID#${PAYPAL_CLIENT_ID}#g" "$ROOT_DIR/env.js"
sed -i "" -e "s#PAYPAL_SECRET#${PAYPAL_SECRET}#g" "$ROOT_DIR/env.js"
sed -i "" -e "s#PAYPAL_PLAN_MONTHLY_1499#${PAYPAL_PLAN_MONTHLY_1499}#g" "$ROOT_DIR/env.js"
sed -i "" -e "s#PAYPAL_PLAN_ANNUAL_4999#${PAYPAL_PLAN_ANNUAL_4999}#g" "$ROOT_DIR/env.js"
sed -i "" -e "s#PAYPAL_WEBHOOK_ID#${PAYPAL_WEBHOOK_ID}#g" "$ROOT_DIR/env.js"
sed -i "" -e "s#CRISP_WEBSITE_ID#${CRISP_WEBSITE_ID}#g" "$ROOT_DIR/env.js"
sed -i "" -e "s#EXOCLICK_ZONE#${EXOCLICK_ZONE}#g" "$ROOT_DIR/env.js"
sed -i "" -e "s#JUICYADS_ZONE#${JUICYADS_ZONE}#g" "$ROOT_DIR/env.js"
sed -i "" -e "s#EROADVERTISING_ZONE#${EROADVERTISING_ZONE}#g" "$ROOT_DIR/env.js"
sed -i "" -e "s#EXOCLICK_SNIPPET_B64#${EXOCLICK_SNIPPET_B64}#g" "$ROOT_DIR/env.js"
sed -i "" -e "s#JUICYADS_SNIPPET_B64#${JUICYADS_SNIPPET_B64}#g" "$ROOT_DIR/env.js"
sed -i "" -e "s#EROADVERTISING_SNIPPET_B64#${EROADVERTISING_SNIPPET_B64}#g" "$ROOT_DIR/env.js"
sed -i "" -e "s#POPADS_SITE_ID#${POPADS_SITE_ID}#g" "$ROOT_DIR/env.js"
sed -i "" -e "s#POPADS_ENABLE#${POPADS_ENABLE}#g" "$ROOT_DIR/env.js"
sed -i "" -e "s#IBG_ASSETS_BASE_URL#${IBG_ASSETS_BASE_URL}#g" "$ROOT_DIR/env.js"

rm -f "$ROOT_DIR/tools/env.js"
echo "OK: env.js generado en raíz"
