import { writeFileSync } from 'fs';
const v = process.env;
const IBG = {
  PAYPAL_CLIENT_ID: v.PAYPAL_CLIENT_ID || '',
  PAYPAL_SECRET: v.PAYPAL_SECRET || '',
  PAYPAL_PLAN_MONTHLY_1499: v.PAYPAL_PLAN_MONTHLY_1499 || '',
  PAYPAL_PLAN_ANNUAL_4999: v.PAYPAL_PLAN_ANNUAL_4999 || '',
  PAYPAL_WEBHOOK_ID: v.PAYPAL_WEBHOOK_ID || '',
  CRISP_WEBSITE_ID: v.CRISP_WEBSITE_ID || '',
  EXOCLICK_ZONE: v.EXOCLICK_ZONE || '',
  JUICYADS_ZONE: v.JUICYADS_ZONE || '',
  EROADVERTISING_ZONE: v.EROADVERTISING_ZONE || '',
  EXOCLICK_SNIPPET_B64: v.EXOCLICK_SNIPPET_B64 || '',
  JUICYADS_SNIPPET_B64: v.JUICYADS_SNIPPET_B64 || '',
  EROADVERTISING_SNIPPET_B64: v.EROADVERTISING_SNIPPET_B64 || '',
  POPADS_SITE_ID: v.POPADS_SITE_ID || '',
  POPADS_ENABLE: v.POPADS_ENABLE || '',
  IBG_ASSETS_BASE_URL: v.IBG_ASSETS_BASE_URL || '',
  CURRENCY: 'EUR'
};
writeFileSync('ibg-env.js', 'window.IBG = ' + JSON.stringify(IBG, null, 2) + ';');
console.log('[IBG] ibg-env.js generado');
