/**
 * tools/inject_env.mjs — NO-OP seguro para Vercel build.
 * - Evita el error "Cannot find module '/vercel/path0/tools/inject_env.mjs'".
 * - Opcionalmente genera/actualiza public/js/env-ads-inline.js a partir de vars de entorno.
 */
import fs from 'node:fs';
import path from 'node:path';

const outDir = path.resolve('public/js');
fs.mkdirSync(outDir, { recursive: true });

const envFile = path.join(outDir, 'env-ads-inline.js');

// Recoge algunas variables si existen; si no, usa defaults actuales
const EXOCLICK_ZONES        = process.env.EXOCLICK_ZONES        || '5696328,5705186';
const EXOCLICK_ZONE         = process.env.EXOCLICK_ZONE         || '5696328';
const EXOCLICK_BOTTOM_ZONE  = process.env.EXOCLICK_BOTTOM_ZONE  || '5717078';
const POPADS_SITE_ID        = process.env.POPADS_SITE_ID        || '5226758';
const POPADS_ENABLE         = (process.env.POPADS_ENABLE ?? '1') === '1' ? 1 : 0;

let js = `// Generated by tools/inject_env.mjs at build time
window.__IBG_ADS = window.__IBG_ADS || {};
Object.assign(window.__IBG_ADS, {
  EXOCLICK_ZONES: ${JSON.stringify(EXOCLICK_ZONES)},
  EXOCLICK_ZONE: ${JSON.stringify(EXOCLICK_ZONE)},
  EXOCLICK_BOTTOM_ZONE: ${JSON.stringify(EXOCLICK_BOTTOM_ZONE)},
  POPADS_SITE_ID: ${JSON.stringify(POPADS_SITE_ID)},
  POPADS_ENABLE: ${JSON.stringify(POPADS_ENABLE)}
});
console.log('IBG_ADS ZONES ->', window.__IBG_ADS);
`;

try {
  // Si ya existe, lo dejamos; si falta o está vacío, lo escribimos
  const exists = fs.existsSync(envFile) && fs.statSync(envFile).size > 0;
  if (!exists) fs.writeFileSync(envFile, js);
  else {
    // Aún así, si quieres forzar regeneración, descomenta la siguiente línea:
    // fs.writeFileSync(envFile, js);
  }
  console.log('[inject_env] ok — env-ads-inline.js listo');
} catch (e) {
  console.warn('[inject_env] warning:', e?.message || e);
  // No fallamos el build por esto: es NO-OP seguro.
}
